name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest -q --alluredir=allure-results --html=pytest_report.html --self-contained-html
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pytest-artifacts
          path: |
            allure-results
            pytest_report.html

  perf:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Locust headless
        run: |
          mkdir -p perf
          locust -f perf/locustfile.py --headless -u 12 -r 6 -t 25s --csv=perf/stats --html perf/report.html
      - name: Gate performance thresholds
        run: |
          python perf/check_thresholds.py perf/stats_stats.csv
      - name: Upload perf artifacts
        uses: actions/upload-artifact@v4
        with:
          name: perf-artifacts
          path: |
            perf/report.html
            perf/stats_stats.csv
